services:
  spotidrome:
    build: .
    container_name: spotidrome
    restart: unless-stopped
    ports:
      - "8095:8095"
    volumes:
      - /data/navidrome/music:/music
      - ./data:/app/data
    environment:
      - MUSIC_DIR=/music
      - DATA_DIR=/app/data
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - YOUTUBE_COOKIES=${YOUTUBE_COOKIES:-}
    labels:
      - traefik.enable=true
      - traefik.http.routers.spotidrome.rule=Host(`dl.lan`)
      - traefik.http.routers.spotidrome.entrypoints=websecure
      - traefik.http.routers.spotidrome.tls=true
      - traefik.http.services.spotidrome.loadbalancer.server.port=8095
