[project]
name = "spotidrome"
version = "1.0.0"
description = "Spotidrome - A web application for downloading Spotify playlists and albums"
authors = [
    { name = "Yash Agarwal", email = "13733968+yashhere@users.noreply.github.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.128.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "mutagen>=1.47.0",
    "python-multipart>=0.0.22",
    "spotipy>=2.25.2",
    "uvicorn[standard]>=0.40.0",
    "yt-dlp[default]>=2025.12.8",
    "langdetect>=1.0.9",
    "python-dotenv>=1.2.1",
]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
target-version = "py312"
